scan_filter:
  ros__parameters:
    filter1:
      name: remove_rear_blind_zone
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -1.484  # -85 degrees
        upper_angle: 1.484   # +85 degrees
