controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.694
    wheel_radius: 0.064

    use_stamped_vel: false

    # Tuning multipliers for physical slippage/friction
    wheel_separation_multiplier: 0.85
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.09     # Matched to odometry calibration speed
    linear.x.min_velocity: -0.09
    linear.x.max_acceleration: 0.1
    linear.x.min_acceleration: -0.1
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.19    # Matched to odometry calibration turn speed
    angular.z.min_velocity: -0.19
    angular.z.max_acceleration: 0.2
    angular.z.min_acceleration: -0.2
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: